sudo: false
notifications:
  slack:
    secure: ZHRHwEmv0B5pu3HxFPTkk70chHxupN45X8CkMtY6PTapMatICxRIIJNDhUWZGepmkXZB/JnXM7f4pKQe3p83jGLTM4PCQJCoHju9G6yus3swiS6JXQ85UN/acL4K9DegFZPGEi+PtA5gvVP/4HMwOeursbgrm4ayXgXGQUx94cM=
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - git
      - python-pip
      - libopenmpi-dev
      - openmpi-bin
      - libblas-dev
      - liblapack-dev
      - gfortran
env:
  global:
    - CC=mpicc
    - PETSC_CONFIGURE_OPTIONS="--with-debugging=1"
# command to install dependencies
before_install:
  - pip install --upgrade pip
  # Force installation of requirements IN THE ORDER WE SPECIFIED!  AAAARGH.
  - "xargs -l1 pip install < requirements-ext.txt"
  - "xargs -l1 pip install < requirements-git.txt"
  - pip install pulp
  - pip install -U flake8
install:
  - pip install -e .
# command to run tests
script:
  - make lint
  - py.test test -v --tb=native
