# pyop2 default configuration

log_level: WARN

lazy_evaluation: true
lazy_max_trace_length: 0

backend: sequential

debug: 0

# codegen
dump-gencode: false
dump-gencode-path: /tmp/%(kernel)s-%(time)s.cl.c
