name: CI

# Trigger the workflow on push or pull request,
# but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CC: mpicc
      PETSC_CONFIGURE_OPTIONS: --with-debugging=1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        shell: bash
        run: |
          sudo apt install  \
            build-essential python3-dev git python3-pip libopenmpi-dev  \
            openmpi-bin libblas-dev liblapack-dev gfortran

      - name: Set correct Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      # xargs is used to force installation of requirements in the order we specified.
      # pip 20.2 needed for loopy install to work.
      - name: Install Python dependencies
        shell: bash
        run: |
          pip install pip==20.2
          xargs -l1 pip install < requirements-ext.txt
          xargs -l1 pip install < requirements-git.txt
          pip install pulp
          pip install -U flake8

      - name: Install PyOP2
        shell: bash
        run: pip install -e .

      - name: Do tests
        shell: bash
        run: |
          make lint
          py.test test -v --tb=native
